name: Publish REST ML Service to GHCR
on:
  pull_request:
    types: [closed]
jobs:
  publish-to-ghcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - 
        name: Login to GHCR.IO
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "yaizaromero"
          password: ${{ secrets.PAT }}
    - 
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/yaizaromero/log_predict:1.0
